# Generate BuildInfo's Git inputs at build time. The output is replaced only
# when its contents change so this script may safely run for every build.

if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "SOURCE_DIR and OUTPUT_FILE are required")
endif()

set(GIT_COMMIT_HASH "")
set(GIT_BRANCH "")
set(GIT_DIRTY_INT 0)

if(DEFINED GIT_EXECUTABLE AND NOT GIT_EXECUTABLE STREQUAL "")
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse HEAD
    RESULT_VARIABLE GIT_COMMIT_RESULT
    OUTPUT_VARIABLE GIT_COMMIT_HASH
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  if(NOT GIT_COMMIT_RESULT EQUAL 0)
    set(GIT_COMMIT_HASH "")
  endif()

  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --abbrev-ref HEAD
    RESULT_VARIABLE GIT_BRANCH_RESULT
    OUTPUT_VARIABLE GIT_BRANCH
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  if(NOT GIT_BRANCH_RESULT EQUAL 0)
    set(GIT_BRANCH "")
  endif()

  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" status --porcelain
    RESULT_VARIABLE GIT_STATUS_RESULT
    OUTPUT_VARIABLE GIT_STATUS_OUTPUT
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  if(GIT_STATUS_RESULT EQUAL 0 AND NOT GIT_STATUS_OUTPUT STREQUAL "")
    set(GIT_DIRTY_INT 1)
  endif()
endif()

function(c_string_escape INPUT_NAME OUTPUT_NAME)
  set(VALUE "${${INPUT_NAME}}")
  string(REPLACE "\\" "\\\\" VALUE "${VALUE}")
  string(REPLACE "\"" "\\\"" VALUE "${VALUE}")
  string(REPLACE "\n" "\\n" VALUE "${VALUE}")
  set(${OUTPUT_NAME} "${VALUE}" PARENT_SCOPE)
endfunction()

c_string_escape(GIT_COMMIT_HASH GIT_COMMIT_HASH_ESCAPED)
c_string_escape(GIT_BRANCH GIT_BRANCH_ESCAPED)

set(CONTENT "// Auto-generated by cmake/GenerateGitProvenance.cmake.\n")
string(APPEND CONTENT "#ifndef XRPL_PROTOCOL_BUILDINFOGENERATED_H_INCLUDED\n")
string(APPEND CONTENT "#define XRPL_PROTOCOL_BUILDINFOGENERATED_H_INCLUDED\n\n")
string(APPEND CONTENT "#ifndef GIT_COMMIT_HASH\n")
string(APPEND CONTENT "#define GIT_COMMIT_HASH \"${GIT_COMMIT_HASH_ESCAPED}\"\n")
string(APPEND CONTENT "#endif\n")
string(APPEND CONTENT "#ifndef GIT_BRANCH\n")
string(APPEND CONTENT "#define GIT_BRANCH \"${GIT_BRANCH_ESCAPED}\"\n")
string(APPEND CONTENT "#endif\n")
string(APPEND CONTENT "#ifndef GIT_DIRTY\n")
string(APPEND CONTENT "#define GIT_DIRTY ${GIT_DIRTY_INT}\n")
string(APPEND CONTENT "#endif\n\n")
string(APPEND CONTENT "#endif\n")

get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(TEMP_FILE "${OUTPUT_FILE}.tmp")
file(WRITE "${TEMP_FILE}" "${CONTENT}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${TEMP_FILE}" "${OUTPUT_FILE}"
  COMMAND_ERROR_IS_FATAL ANY
)
file(REMOVE "${TEMP_FILE}")
